"""empty message

Revision ID: fdd881e98823
Revises: ed9a4e009c79
Create Date: 2022-09-27 14:40:58.722336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd881e98823'
down_revision = 'ed9a4e009c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UMS_USER_ADDRESS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_line_1', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pin', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UMS_USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UMS_USER_ADDRESS')
    # ### end Alembic commands ###
